### ISSUE TITLE
Clicking near the filename in "Files" has an unexpected result

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#17]
When selecting on a file for download you can click the download icon or the filename itself. Clicking in the grey area to the right of the filename does nothing as expected but clicking just above or below the filename inside the grey pulls up the "Add files" function. The behavior in this area should either be do nothing or download the file.

**Comment by jcoffland** [comment]
This one took me awhile to figure out.  It turns out that this only affects one small rectangle on the file-manager.  It's shim injected by plupload.  I don't know why it's needed by I was able to push it out of the way.
