### ISSUE TITLE
Profile page not found

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#18]
After changing the name of a project I now receive a "Sorry page not found" when clicking on my profile. 

 https://test.buildbotics.com/sam.coffland#profile

**Comment by jcoffland** [comment]
I just fixed this.  Any idea how you got all that weird data in your bio?  I had to clear your profile's bio field.  It would be great to figure out how to reproduce this.

**Comment by scofflan** [comment]
While trying to upload a photo to my profile I tried to drag and drop a jpg. It does not drop on the photo area but does drop in the Bio text area. This produce the raw code for the jpg.

**Comment by jcoffland** [comment]
Wow, that's a good one.  I found a few things from this:
1. The middle layer is not talking to the DB using the same character set. (UTF-8) [buildbotics/buildbotics/issues/4](https://github.com/buildbotics/buildbotics/issues/4)
2. I need better limits on the bio input. #20
3. Uploading to an image via drag-n-drop would be a nice feature on the profile page.  #19
4. markdown editor needs to have drag-n-drop disabled. #21
