### ISSUE TITLE
Login through github fails

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#25]
When attempting to login using github after authenticating you are brought back to the home screen and still not logged in.

**Comment by jcoffland** [comment]
Strange, it works fine for me.  Do you have any more info on this?  Perhaps there is something particular about your account that Buildbotics does not like.

**Comment by jcoffland** [comment]
Can you try this with your browser's debug console open?  Hit F12 and select the _Console_ tab.  Then try to login with GitHub.

I wasn't able to find a record of your login attempt either in the DB or middle-layer logs.  I found your IP in the Web server logs, accessing the github login, but I cannot tell what went wrong.

**Comment by jcoffland** [comment]
Actually after digging a little deeper I was able to find errors in the buildbotics logs.  It turns out that GitHub does not always set the `name` field in the profile data it sends.  However, it always has a `login` field.

This should be fixed now.  Reopen this ticket if not.
