### ISSUE TITLE
Adding files into another accounts projects allows drag and drop

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#26]
This is a nit picky bug

Users can attempt to upload files for another users project. Although uploads do get added they are allowed to drag and drop and appear to be added. Only when coming back to the project can you tell that the files were not added. 

Not allowing the drag and drop for another users project would be a more clear response.

**Comment by jcoffland** [comment]
That's a good one.  I'll have to disable drag-n-drop for non-owners.

**Comment by jcoffland** [comment]
I also noticed that a recent type-o causes the 'Add Files' button and dropzone to appear even if the user is not the owner.
