### ISSUE TITLE
Terms, privacy, and contact are relative links

### ISSUE THREAD

**Issue by scofflan** [buildbotics/buildbotics-ui#28]
These links are not yet implemented on the main page but they are not correct when accessed form any other pages. 

The following is the link shown for privacy from the buildbotics_logo's files page.

https://test.buildbotics.com/Doug/Buildbotics_Logo#privacy

It should instead be.

https://test.buildbotics.com/#privacy

**Comment by jcoffland** [comment]
Mainly this is just not yet done.  One issue I haven't yet decided on is where exactly to place these.  If I put them at `buildbotics.com/privacy` then `privacy` is not a usable user name.  Which might be ok.  Right now `create`, `learn` and `explore` are not valid user names.

It is currently possible to create these users but then you wont be able to access their profiles. See: buildbotics/buildbotics/issues/7
