### ISSUE TITLE
Can't add picture of myself for  my profile

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#31]
I can't find a way to add a picture of myself for my profile.  I tried dragging and dropping a picture in but it just takes over the entier screen.  There doesn't seem to be any obvious way to do this in the profile edit page.

**Comment by jcoffland** [comment]
The issue is that you have to change your profile picture on the account you logged in with (Google, Facebook or GitHub).  Then it will update.

Either we need to allow people to set their profile picture on Buildbotics or explain this better.

**Comment by DougCoffland** [comment]
I changed my picture on Google, but I still get the standard icon at BB.

**Comment by jcoffland** [comment]
It might depend on who you used to login.  I know you can change your photo if you use Facebook.  Betany did it.  Probably the solution is to just allow people to change their Buildbotics profile picture directly.

**Comment by DougCoffland** [comment]
I don't have a facebook account.  I suppose it's about time to get one.

**Comment by jcoffland** [comment]
See #19.

**Comment by jcoffland** [comment]
Fixed.
