### ISSUE TITLE
Hard to get back to display all creations after searching

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#32]
After entering a search string in the search field on the Creations page, I am taken to the appropriate project.  I entered "emboss" and was taken to my Buildbotics project based on the keyword search.  I then wanted to get back to the Creations page, so I clicked Creations.  It continued to only show my Buildbotics Logo project.  After some playing around, I realized that the word "emboss" was still in the search field.  After clearing the search field, it showed all fields.

I recommend clearing the search field after the search is conducted.  This would lead to more intuitive behavior.

**Comment by jcoffland** [comment]
That makes sense.  I'll fix this.
