### ISSUE TITLE
Update avatars when starring and unstarring

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#34]
This is a very minor issue.  I noticed that in the project page "/Doug/Buildbotics_Logo", I can click star and the star count immediately updates.  The avatars in the information block are not updated until I refresh the page.  It would be better if the avatar list updated without having to refresh the page.

**Comment by jcoffland** [comment]
I noticed this too.

**Comment by jcoffland** [comment]
Fixed.
