### ISSUE TITLE
Edit Profile button remains on tabs

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#36]
While logged and working in the Profile tab under /Doug the "Edit Profile" button is present.  This is good.  When I clicked "Creations" I expected it to go away and possibly turn into Edit Creation.  The button remained as "Edit Profile".  It would be probably be best to remove the button on all tabs except for the Profile tab.

**Comment by jcoffland** [comment]
I'm working on a set changes that fixes this.

**Comment by jcoffland** [comment]
Fixed
