### ISSUE TITLE
Starring project strange behaviour when not logged in

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#48]
I noticed that if I go to the Creations paged when not logged in and hover over the star for a project, the tooltip says "Star this project".  When I click it, the page goes a little bit dim and the star count does not changed.  It is appropriate that it would not change, but it should tell the user that they needed to log in to do it.

**Comment by jcoffland** [comment]
Good catch.  I'll take care of this.

**Comment by jcoffland** [comment]
Fixed
