### ISSUE TITLE
File Upload Failure

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#52]
I decided to remove the Buildbotics_logo project and rebuild it using the new steps feature.  In doing so, I first deleted the project, which went fine.  Then, I started a new project at BB_Logo and gave it a title of "Buildbotics Logo".  Then, I went to Files while editing and selected four files (bbl.nc, bbl.tpl, bbl.xml, and buildbotics_logo.png).  The loading begins, but then fails with a pop-up dialog that says "Failed to upload file bbl.xml" and "{"readyState":4,"responseText":"DB:1213: Deadlock found when trying to get lock; try restarting transaction","status":500,"statusText":"HTTP_INTERNAL_SERVER_".

I am unable to dismiss the dialog by clicking "OK".  I can move to other pages on test.buildbotics.com and the dialog remains in the center of the page.  One way to get rid of it is to completely leave the site, but it is still there if I hit the back button.  Another way to git rid of it is to refresh the browser.

Finally, I am able to successfully add the other two files by clicking the "+Add Files" button again.

**Comment by jcoffland** [comment]
I've seen this error before.  I need to track this down.  The DB gets this deadlock error occasionally.  I'm not sure why.

**Comment by jcoffland** [comment]
See: http://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans

**Comment by jcoffland** [comment]
The error dialog problem is another issue.  See #55.

**Comment by jcoffland** [comment]
I think I fixed this but since I cannot reproduce the deadlock we'll just have to wait and see.  If a DB deadlock occurs it should log a warning and retry it.
