### ISSUE TITLE
Strange cursor behavior when editing steps in a project

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#54]
I am having a lot of trouble adding steps to the BB_Logo draft project.  The first step (introduction) seems to go OK.  In subsequent steps, the text does not show as I type it in.  It does appear when I preview, but it is very difficult to edit it without being able to see what you are typing.  In the second step (Tools), the text seems to scroll off the left side of the page, giving the impression that nothing is being typed because the cursor stays at the left edge.  If I use my arrow keys to move left, however, the text appears.  Even that doesn't work in the third step.

**Comment by jcoffland** [comment]
Works for me.  Do you have any more details.  You're using Firefox right?  Can you provide screenshots?

**Comment by DougCoffland** [comment]
I do use firefox.  I don't think the screenshots would be very informative, because when I type I don't get anything on the screen.  I think we may need to talk this one through on the phone.

**Comment by jcoffland** [comment]
Not happening now.

**Comment by DougCoffland** [comment]
I am having this problem again.  I've noticed that it happens everytime if I use Iceweasel on my Debian system.  I do not have the problem with Chrome on Debian and I do not have the problem with firefox on Windows.

The error console (F12) shows no errors.

**Comment by jcoffland** [comment]
I removed the steps editor.  You might need to do a hard reload on your browser.

**Comment by DougCoffland** [comment]
sounds good,

Thanks
