### ISSUE TITLE
Cannot close error dialog

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/buildbotics-ui#55]
Doug wrote:

> I am unable to dismiss the dialog by clicking "OK". I can move to other pages on test.buildbotics.com and the dialog remains in the center of the page. One way to get rid of it is to completely leave the site, but it is still there if I hit the back button. Another way to git rid of it is to refresh the browser.

**Comment by jcoffland** [comment]
I'm unable to reproduce this.  Can you reproduce this?  If so please do so with your browser's debug console open.  You can open the debug console by pressing F12.  I expect there is some sort of error in the console.

**Comment by DougCoffland** [comment]
It's working correctly now.  The files upload without an error, so I cannot
recreate the dialog.

**Comment by jcoffland** [comment]
Fixed
